/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedConhecimentoRouteImport } from './routes/_authenticated/conhecimento'
import { Route as AuthenticatedConsultoresRouteImport } from './routes/_authenticated/consultores'
import { Route as AuthenticatedConversasRouteImport } from './routes/_authenticated/conversas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFilaRouteImport } from './routes/_authenticated/fila'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedMinhaConexaoRouteImport } from './routes/_authenticated/minha-conexao'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedPlataformaRouteImport } from './routes/_authenticated/plataforma'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedWhatsappRouteImport } from './routes/_authenticated/whatsapp'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as AuthenticatedVerComoUserIdRouteImport } from './routes/_authenticated/ver-como.$userId'
import { Route as ApiPublicQueueTickRouteImport } from './routes/api/public/queue/tick'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp/webhook'
import { Route as ApiPublicWhatsappWebhookTokenRouteImport } from './routes/api/public/whatsapp/webhook.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConhecimentoRoute =
  AuthenticatedConhecimentoRouteImport.update({
    id: '/conhecimento',
    path: '/conhecimento',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConsultoresRoute =
  AuthenticatedConsultoresRouteImport.update({
    id: '/consultores',
    path: '/consultores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConversasRoute = AuthenticatedConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFilaRoute = AuthenticatedFilaRouteImport.update({
  id: '/fila',
  path: '/fila',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMinhaConexaoRoute =
  AuthenticatedMinhaConexaoRouteImport.update({
    id: '/minha-conexao',
    path: '/minha-conexao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlataformaRoute = AuthenticatedPlataformaRouteImport.update({
  id: '/plataforma',
  path: '/plataforma',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWhatsappRoute = AuthenticatedWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVerComoUserIdRoute =
  AuthenticatedVerComoUserIdRouteImport.update({
    id: '/ver-como/$userId',
    path: '/ver-como/$userId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicQueueTickRoute = ApiPublicQueueTickRouteImport.update({
  id: '/api/public/queue/tick',
  path: '/api/public/queue/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappWebhookTokenRoute =
  ApiPublicWhatsappWebhookTokenRouteImport.update({
    id: '/$token',
    path: '/$token',
    getParentRoute: () => ApiPublicWhatsappWebhookRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conhecimento': typeof AuthenticatedConhecimentoRoute
  '/consultores': typeof AuthenticatedConsultoresRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/minha-conexao': typeof AuthenticatedMinhaConexaoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plataforma': typeof AuthenticatedPlataformaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/ver-como/$userId': typeof AuthenticatedVerComoUserIdRoute
  '/api/public/queue/tick': typeof ApiPublicQueueTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/whatsapp/webhook/$token': typeof ApiPublicWhatsappWebhookTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/conhecimento': typeof AuthenticatedConhecimentoRoute
  '/consultores': typeof AuthenticatedConsultoresRoute
  '/conversas': typeof AuthenticatedConversasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/fila': typeof AuthenticatedFilaRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/minha-conexao': typeof AuthenticatedMinhaConexaoRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/plataforma': typeof AuthenticatedPlataformaRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/whatsapp': typeof AuthenticatedWhatsappRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/ver-como/$userId': typeof AuthenticatedVerComoUserIdRoute
  '/api/public/queue/tick': typeof ApiPublicQueueTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/whatsapp/webhook/$token': typeof ApiPublicWhatsappWebhookTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/conhecimento': typeof AuthenticatedConhecimentoRoute
  '/_authenticated/consultores': typeof AuthenticatedConsultoresRoute
  '/_authenticated/conversas': typeof AuthenticatedConversasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/fila': typeof AuthenticatedFilaRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/minha-conexao': typeof AuthenticatedMinhaConexaoRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/plataforma': typeof AuthenticatedPlataformaRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/whatsapp': typeof AuthenticatedWhatsappRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_authenticated/ver-como/$userId': typeof AuthenticatedVerComoUserIdRoute
  '/api/public/queue/tick': typeof ApiPublicQueueTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRouteWithChildren
  '/api/public/whatsapp/webhook/$token': typeof ApiPublicWhatsappWebhookTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/conhecimento'
    | '/consultores'
    | '/conversas'
    | '/dashboard'
    | '/fila'
    | '/leads'
    | '/minha-conexao'
    | '/onboarding'
    | '/plataforma'
    | '/relatorios'
    | '/whatsapp'
    | '/convite/$token'
    | '/ver-como/$userId'
    | '/api/public/queue/tick'
    | '/api/public/whatsapp/webhook'
    | '/api/public/whatsapp/webhook/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/configuracoes'
    | '/conhecimento'
    | '/consultores'
    | '/conversas'
    | '/dashboard'
    | '/fila'
    | '/leads'
    | '/minha-conexao'
    | '/onboarding'
    | '/plataforma'
    | '/relatorios'
    | '/whatsapp'
    | '/convite/$token'
    | '/ver-como/$userId'
    | '/api/public/queue/tick'
    | '/api/public/whatsapp/webhook'
    | '/api/public/whatsapp/webhook/$token'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/configuracoes'
    | '/_authenticated/conhecimento'
    | '/_authenticated/consultores'
    | '/_authenticated/conversas'
    | '/_authenticated/dashboard'
    | '/_authenticated/fila'
    | '/_authenticated/leads'
    | '/_authenticated/minha-conexao'
    | '/_authenticated/onboarding'
    | '/_authenticated/plataforma'
    | '/_authenticated/relatorios'
    | '/_authenticated/whatsapp'
    | '/convite/$token'
    | '/_authenticated/ver-como/$userId'
    | '/api/public/queue/tick'
    | '/api/public/whatsapp/webhook'
    | '/api/public/whatsapp/webhook/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
  ApiPublicQueueTickRoute: typeof ApiPublicQueueTickRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conhecimento': {
      id: '/_authenticated/conhecimento'
      path: '/conhecimento'
      fullPath: '/conhecimento'
      preLoaderRoute: typeof AuthenticatedConhecimentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consultores': {
      id: '/_authenticated/consultores'
      path: '/consultores'
      fullPath: '/consultores'
      preLoaderRoute: typeof AuthenticatedConsultoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conversas': {
      id: '/_authenticated/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof AuthenticatedConversasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fila': {
      id: '/_authenticated/fila'
      path: '/fila'
      fullPath: '/fila'
      preLoaderRoute: typeof AuthenticatedFilaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/minha-conexao': {
      id: '/_authenticated/minha-conexao'
      path: '/minha-conexao'
      fullPath: '/minha-conexao'
      preLoaderRoute: typeof AuthenticatedMinhaConexaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plataforma': {
      id: '/_authenticated/plataforma'
      path: '/plataforma'
      fullPath: '/plataforma'
      preLoaderRoute: typeof AuthenticatedPlataformaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/whatsapp': {
      id: '/_authenticated/whatsapp'
      path: '/whatsapp'
      fullPath: '/whatsapp'
      preLoaderRoute: typeof AuthenticatedWhatsappRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ver-como/$userId': {
      id: '/_authenticated/ver-como/$userId'
      path: '/ver-como/$userId'
      fullPath: '/ver-como/$userId'
      preLoaderRoute: typeof AuthenticatedVerComoUserIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/queue/tick': {
      id: '/api/public/queue/tick'
      path: '/api/public/queue/tick'
      fullPath: '/api/public/queue/tick'
      preLoaderRoute: typeof ApiPublicQueueTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/webhook/$token': {
      id: '/api/public/whatsapp/webhook/$token'
      path: '/$token'
      fullPath: '/api/public/whatsapp/webhook/$token'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookTokenRouteImport
      parentRoute: typeof ApiPublicWhatsappWebhookRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedConhecimentoRoute: typeof AuthenticatedConhecimentoRoute
  AuthenticatedConsultoresRoute: typeof AuthenticatedConsultoresRoute
  AuthenticatedConversasRoute: typeof AuthenticatedConversasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFilaRoute: typeof AuthenticatedFilaRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedMinhaConexaoRoute: typeof AuthenticatedMinhaConexaoRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedPlataformaRoute: typeof AuthenticatedPlataformaRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedWhatsappRoute: typeof AuthenticatedWhatsappRoute
  AuthenticatedVerComoUserIdRoute: typeof AuthenticatedVerComoUserIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedConhecimentoRoute: AuthenticatedConhecimentoRoute,
  AuthenticatedConsultoresRoute: AuthenticatedConsultoresRoute,
  AuthenticatedConversasRoute: AuthenticatedConversasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFilaRoute: AuthenticatedFilaRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedMinhaConexaoRoute: AuthenticatedMinhaConexaoRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedPlataformaRoute: AuthenticatedPlataformaRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedWhatsappRoute: AuthenticatedWhatsappRoute,
  AuthenticatedVerComoUserIdRoute: AuthenticatedVerComoUserIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicWhatsappWebhookRouteChildren {
  ApiPublicWhatsappWebhookTokenRoute: typeof ApiPublicWhatsappWebhookTokenRoute
}

const ApiPublicWhatsappWebhookRouteChildren: ApiPublicWhatsappWebhookRouteChildren =
  {
    ApiPublicWhatsappWebhookTokenRoute: ApiPublicWhatsappWebhookTokenRoute,
  }

const ApiPublicWhatsappWebhookRouteWithChildren =
  ApiPublicWhatsappWebhookRoute._addFileChildren(
    ApiPublicWhatsappWebhookRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ConviteTokenRoute: ConviteTokenRoute,
  ApiPublicQueueTickRoute: ApiPublicQueueTickRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
